server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://carrotmarket-db-1.c23lradn2sla.ap-northeast-2.rds.amazonaws.com/carrotmarket # 변경해주세요
    username:  admin
    password:  dptmxmfk12!24
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전